# Generated by Django 6.0.1 on 2026-02-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField()),
                ('CategoryImage', models.ImageField(upload_to='categories')),
            ],
        ),
    ]
