# Generated by Django 6.0.1 on 2026-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('Image', models.ImageField(upload_to='services')),
            ],
        ),
    ]
