# Generated by Django 6.0.1 on 2026-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(blank=True, max_length=200, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('Phone', models.CharField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
