# Generated by Django 6.0.1 on 2026-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Grandtotal',
            field=models.CharField(blank=True, null=True),
        ),
    ]
